#!/usr/bin/env bash
# bin/compile <build-dir> <cache-dir>

# Fail fast
set -e

# Debug
# set -x

BUILD_DIR=$1
CACHE_DIR=$2
VENDOR_DIR="$BUILD_DIR/vendor"
TALIB_DIR="$BUILD_DIR/vendor/ta-lib"

function setDefaultEnv (){
  echo "export $1=/app/vendor/$2:\$$1" >> $PROFILE_PATH
  echo "export $1=/app/vendor/$2:\$$1" >> $EXPORT_PATH
}

echo "=====> Getting talib sources"
curl "https://netix.dl.sourceforge.net/project/ta-lib/ta-lib/0.4.0/ta-lib-0.4.0-src.tar.gz" -s -o - | tar -xvzf - -C "$VENDOR_DIR"

echo "=====> Compiling talib"
cd $TALIB_DIR
chmod +x configure
./configure LDFLAGS="-lm"
make
make install

echo "=====> Getting talib_ruby"
env ARCHFLAGS="-arch x86_64" gem install talib_ruby -- --with-talib-include=/app/vendor/ta-lib/c/include  --with-talib-lib=/app/vendor/ta-lib/c/lib






